CREATE TABLE PRODUTO(
CODIGO NUMBER(4),
CATEGORIA CHAR(1),
VALOR NUMBER(4,2)
);
INSERT INTO PRODUTO VALUES(1001,'A',7.55);
INSERT INTO PRODUTO VALUES(1002,'B',5.95);
INSERT INTO PRODUTO VALUES(1003,'C',3.45);


DECLARE
    CURSOR C_AJUSTE IS SELECT * FROM PRODUTO;
    V_CATEGORIA C_AJUSTE%ROWTYPE;
    V_VALOR_AJUSTE NUMBER(4,2);
    V_VALOR_ATUALIZADO NUMBER(4,2);
BEGIN
    OPEN C_AJUSTE;
    LOOP
        FETCH C_AJUSTE INTO V_CATEGORIA;
        EXIT WHEN C_AJUSTE%NOTFOUND;

        IF V_CATEGORIA.CATEGORIA = 'A' THEN
            V_VALOR_AJUSTE := 5*(V_CATEGORIA.VALOR / 100);
            V_VALOR_ATUALIZADO := V_VALOR_AJUSTE + V_CATEGORIA.VALOR;
            UPDATE PRODUTO SET VALOR = V_VALOR_ATUALIZADO WHERE CATEGORIA = V_CATEGORIA.CATEGORIA;
        ELSIF V_CATEGORIA.CATEGORIA = 'B' THEN
            V_VALOR_AJUSTE := 10*(V_CATEGORIA.VALOR / 100);
            V_VALOR_ATUALIZADO := V_VALOR_AJUSTE + V_CATEGORIA.VALOR;
            UPDATE PRODUTO SET VALOR = V_VALOR_ATUALIZADO WHERE CATEGORIA = V_CATEGORIA.CATEGORIA;
        ELSIF V_CATEGORIA.CATEGORIA = 'C' THEN
            V_VALOR_AJUSTE := 15*(V_CATEGORIA.VALOR / 100);
            V_VALOR_ATUALIZADO := V_VALOR_AJUSTE + V_CATEGORIA.VALOR;
            UPDATE PRODUTO SET VALOR = V_VALOR_ATUALIZADO WHERE CATEGORIA = V_CATEGORIA.CATEGORIA;
        END IF;
    END LOOP;
    CLOSE C_AJUSTE;
END;


SELECT * FROM PRODUTO;
DROP TABLE PRODUTO;

